### ISSUE TITLE
Panic if repo contains an invalid semver formatted tag

### ISSUE THREAD

**Issue by chrispruitt** [b4b4r07/git-bump#1]
First off, awesome project! This is going to be really handy.

I did find a small issue. If a tag exists in the repo that is not of semver format it crashes with the error below. I have a and will PR for you to take a look.

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x113b8d9]

goroutine 1 [running]:
github.com/Masterminds/semver/v3.(*Version).Compare(0xc0000ac870, 0x0, 0x1c30008)
        /home/runner/go/pkg/mod/github.com/!masterminds/semver/v3@v3.0.3/version.go:387 +0x79
github.com/Masterminds/semver/v3.(*Version).LessThan(...)
        /home/runner/go/pkg/mod/github.com/!masterminds/semver/v3@v3.0.3/version.go:362
github.com/Masterminds/semver/v3.Collection.Less(...)
        /home/runner/go/pkg/mod/github.com/!masterminds/semver/v3@v3.0.3/collection.go:17
sort.insertionSort(0x1741120, 0xc000134700, 0x0, 0x2)
        /opt/hostedtoolcache/go/1.13.7/x64/src/sort/sort.go:27 +0xc4
sort.quickSort(0x1741120, 0xc000134700, 0x0, 0x2, 0x4)
        /opt/hostedtoolcache/go/1.13.7/x64/src/sort/sort.go:209 +0x201
sort.Sort(0x1741120, 0xc000134700)
        /opt/hostedtoolcache/go/1.13.7/x64/src/sort/sort.go:218 +0x79
main.(*CLI).currentVersion(0xc0000bfee8, 0x1, 0xc0000bfdff, 0xc000126870)
        /home/runner/work/git-bump/git-bump/main.go:247 +0x1db
main.(*CLI).Run(0xc0000bfee8, 0x1b32ea0, 0x0, 0x0, 0x0, 0x1b32ea0)
        /home/runner/work/git-bump/git-bump/main.go:104 +0xef
main.run(0xc00001e1d0, 0x0, 0x0, 0xc000076058)
        /home/runner/work/git-bump/git-bump/main.go:74 +0x132
main.main()
        /home/runner/work/git-bump/git-bump/main.go:59 +0x64```

**Comment by babarot** [comment]
Thanks, merged and then new version has just released: https://github.com/b4b4r07/git-bump/releases/tag/v0.1.1
